### ISSUE TITLE
Connection timed out Error code 522

### ISSUE THREAD

**Issue by sheladiyaniraj** [D3vd/Meme_Api#101]
![image](https://user-images.githubusercontent.com/51854754/210840841-99ad9429-008a-4ad5-bbea-1b5348c87743.png)

Error: Connection timed out Error code 522

**Comment by SteffTek** [comment]
Yep, same for me since 2 days. Server down. Sad.

**Comment by D3vd** [comment]
Hey 
The issue is now fixed and the server is back up!

Apologies for the interruption

**Comment by SteffTek** [comment]
Can confirm, works again just fine ^^

**Comment by sheladiyaniraj** [comment]
Yes working fine!! 🍾
