### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by comoestassergio** [D3vd/Meme_Api#102]
### Hey!
Just started using this cool API yesterday and today it's giving me a **502**. Did the server go down?

**Comment by DAEMANN** [comment]
Same here

**Comment by himanshu007-creator** [comment]
+1

**Comment by Gabocota** [comment]
I'm sorry guys but it think it might've been me :(
I was making a webapp and forgot to place a cooldown in my loop so it sent thousands of requests and maybe the code doesn't have a limiter so I just killed it. It was at the same time I did that that it stopped working.

**Comment by xDragoxboi** [comment]
ahh sh*t lol

**Comment by Kabyss** [comment]
It’s a free service and should’ve been careful not to abuse it. Anyway I hope the author adds some instructions to self host it so people can use it in whatever ways they want.

**Comment by Gabocota** [comment]
It was a finger error 😭
I would be happy to host it myself

**Comment by D3vd** [comment]
Hey the issue has been fixed! The server is back up

The downtime seems to have been caused by excessive requests that the server was unable to handle. 

Sorry for the interruption

**Comment by comoestassergio** [comment]
Thanks a lot!
