### ISSUE TITLE
Error : 404 page not found

### ISSUE THREAD

**Issue by sheladiyaniraj** [D3vd/Meme_Api#107]
![image](https://user-images.githubusercontent.com/51854754/230106906-64007192-021d-410b-8f2b-9cbc1154f236.png)

**Comment by Sansekai** [comment]
Same

**Comment by MDxWARRIORxOP** [comment]
Im getting the same error.

**Comment by D3vd** [comment]
Issue is fixed 
Server is back up

**Comment by sheladiyaniraj** [comment]
thanks 💙💙💙
