### ISSUE TITLE
Looks like no longer works from reddit side.

### ISSUE THREAD

**Issue by DEPSTRCZ** [D3vd/Meme_Api#122]
When accesing the reddit preview the image wont load.

**Comment by Devansh-kajve** [comment]
It loaded when I tried but the image quality was low. I opened the image in new tab and the problem seems to be with the image size.

edit: Nevermind it works right. The preview array in response is sorted from lowest to highest quality image.

**Comment by gerkim62** [comment]
please close this issue as it does not need to be open anymore
