### ISSUE TITLE
Add a profile to deploy to heroku

### ISSUE THREAD

**Issue by F36** [D3vd/Meme_Api#61]

**Comment by R3l3ntl3ss** [comment]
Hey @F36, I use Heroku containers to deploy the application. Running the following commands deploys the app

```bash
heroku container:push web -a meme-api
heroku container:release web -a meme-api
```

I intend to create a CI/CD pipeline to deploy automatically sometime in the future but I hope this helps you for now.

**Comment by F36** [comment]
acctually i made a procfile for my fored repo check it out https://github.com/F36/Meme_Api

**Comment by R3l3ntl3ss** [comment]
Oh sweet. But you have to build locally in order to deploy right?

**Comment by F36** [comment]
no create a heroku app and select deploy from github and select the repo and deploy and put env variablels

**Comment by D3vd** [comment]
I have added Heroku Docker Deploy Action in the latest commit. I hope this fixes this issue.
