### ISSUE TITLE
Image quality feature

### ISSUE THREAD

**Issue by paramtank** [D3vd/Meme_Api#66]
10/10 for the API

Is there any way to get a lesser quality image as i am using it in my android app image view and it sometimes take time to load high quality image or gif.

Thanks for the API 👍

**Comment by D3vd** [comment]
Thanks @paramtank. I am glad you like it.

I should be able to provide a link of lower quality images in the response. I will work on that and let you know once it's done. 

Thanks for the suggestion

**Comment by D3vd** [comment]
Hey, @paramtank I have added a preview key to the response that contains a list of URLs of different dimensions of the image. It is sorted from low-quality to high-quality resolutions. I hope this helped.

**Comment by paramtank** [comment]
Thankyou so much i will update my app once done will share the app😁
