### ISSUE TITLE
[🚑 Incident] The API on heroku is down.

### ISSUE THREAD

**Issue by StackNeverFlow** [D3vd/Meme_Api#67]
Here is everything listed in detail. Please fix asap.
https://code-gitlab.linusl.de/nerdspace/DiscordBot/-/issues/2

**Comment by D3vd** [comment]
Hey @StackNeverFlow,
Are you still facing issues with the API? It seems to be working fine on my end and people are able to access it. 

`java.net.UnknownHostException` happens when your DNS is unable to resolve the IP. Could you please check and get back?

**Comment by StackNeverFlow** [comment]
Now it's operating again. I don't know if the issue is DNS related.
