### ISSUE TITLE
I have a problem we’re the image won’t show

### ISSUE THREAD

**Issue by phenoxbird** [D3vd/Meme_Api#69]
So I coded your api and when I run the command no image shows and I'm using r/dankmemes so I don't know what's wrong

**Comment by D3vd** [comment]
Can you please describe the exact error that you are getting? The API seems to be working fine for others.

**Comment by phenoxbird** [comment]
I have used the api and when i use it a image does not show up it's just a black bar> Can you please describe the exact error that you are getting? The API seems to be working fine for others.

**Comment by D3vd** [comment]
Can you please give me more context about your problem? I am unable to understand the issue you are facing.

**Comment by phenoxbird** [comment]
So when I use api a image does not show up that's really it

**Comment by D3vd** [comment]
The API gives you only the link to the image which you can use in your app. Please refer to the Readme

**Comment by D3vd** [comment]
Closing this issue for now. Feel free to open if you are still facing any more issues.
