### ISSUE TITLE
Api down?

### ISSUE THREAD

**Issue by paramtank** [D3vd/Meme_Api#70]
Api is not retrieving image url. Is something wrong?

**Comment by D3vd** [comment]
Hey @paramtank, the API seems to be working, can you try again? What's the exact error you are getting?

**Comment by paramtank** [comment]
![image](https://user-images.githubusercontent.com/48821176/98511208-64fc0000-228a-11eb-9d48-7d4d6a737094.png)

Api link not working

**Comment by paramtank** [comment]
you can check it on my App.... :)

https://play.google.com/store/apps/details?id=com.digitank.Sabreddit

**Comment by D3vd** [comment]
Hey @paramtank, I just tried out your app and it seems to be working fine. I am not sure why you are facing this issue on your browser..

Great app by the way.

**Comment by paramtank** [comment]
I guess not working in india.it worked with vpn 😔

**Comment by paramtank** [comment]
Hey there i got what was the problem.i think my wifi service provider has blocked this url as it works fine in mobile net.thank you for the help😁
