### ISSUE TITLE
API backend and question

### ISSUE THREAD

**Issue by lukaIvanic** [D3vd/Meme_Api#73]
Hi, no issue here, just wanted to ask if there's a way to see all the available subreddits. And also could you explain how your API works a little? Do you scrape the site manually or what's going on here? Thanks

**Comment by D3vd** [comment]
Hey @lukaIvanic,

There is no option in this API to do so. You can check this website if it helps [redditlist](http://redditlist.com/all).

I am directly interacting with the Reddit API through their oauth URL `https://oauth.reddit.com/r/<subreddit>` and parsing the results from the response.
You can take a look at it here [get_post.go](https://github.com/D3vd/Meme_Api/blob/master/libraries/reddit/get_posts.go).
