### ISSUE TITLE
Does the url only contain .jpg/.gif

### ISSUE THREAD

**Issue by rahulsain** [D3vd/Meme_Api#77]
If any other is supported please tell

**Comment by alfawal** [comment]
this one is png
![2021-04-20 09_51_35-Window](https://user-images.githubusercontent.com/61620817/115350761-2ca80880-a1be-11eb-8075-dcb317033dac.png)

**Comment by rahulsain** [comment]
> this one is png
> ![2021-04-20 09_51_35-Window](https://user-images.githubusercontent.com/61620817/115350761-2ca80880-a1be-11eb-8075-dcb317033dac.png)

Actually I design my app to distinguish between image and gif only. If any other is supported then I would have to change my implementation.

**Comment by JaffaCakes118** [comment]
Yes it does, it contains .gif and .jpeg in the url, just refresh the page a couple of times and you should get one.
