### ISSUE TITLE
Shows Application error

### ISSUE THREAD

**Issue by MrFiend179** [D3vd/Meme_Api#96]
I've been using this meme api lately but recently it's been giving me an error whenever I use it I fetch it in js but it returns with no response so I opened it the meme api link myself and it showed application error idk if that's a bug or error but it's kinds annoying that the api won't work

**Comment by D3vd** [comment]
Hey, sorry for the inconvenience. Heroku has stopped support for the free dynos, so the old domain has stopped working.
Check out the README.md to update to the new domain
