### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by PureMids** [D3vd/Meme_Api#98]
Im currently using this API for a discord bot, and it was working fine when it was on heroku, but since its switched to meme-api.com, Ive been getting the error: HTTP Error 403: Forbidden

Any help is appreciated. Thanks 

![image](https://user-images.githubusercontent.com/97375993/206100520-6ab23a72-2489-472c-b649-2a7ea716c713.png)

**Comment by D3vd** [comment]
Hey

What route are you calling? 
Also can you share the client side code you are using to call the API?

**Comment by PureMids** [comment]
> Hey
> 
> What route are you calling? Also can you share the client side code you are using to call the API?

Hey. Sorry for the late response. You can view my code [here](https://mystb.in/PercentageObservationsArray)

I forgot to mention im using discord.py (python). As seen in my code, I am calling https://meme-api.com/gimme

**Comment by purrre** [comment]
> Hey
> 
> What route are you calling? Also can you share the client side code you are using to call the API?

Hey. Sorry for the late reply. Also a misclick on closing this.

You can view my code [here](https://mystb.in/PercentageObservationsArray)

Also I forgot to mention im using discord.py (python). As seen in the code I am calling https://meme-api.com/gimme

**Comment by walteij** [comment]
I'm using pretty much the same code, and am facing the same issue;

`    @commands.command()
    async def meme(self, ctx):
        memeAPI = urllib.request.urlopen('https://meme-api.com/gimme/formuladank')
        memeData= json.load(memeAPI)
        memeUrl = memeData['url']
        memeName = memeData['title']
        memePoster = memeData['author']
        memeSub = memeData['subreddit']
        memeLink = memeData['postLink']
        embed = discord.Embed(title=memeName, colour=discord.Colour.orange())
        embed.set_image(url=memeUrl)
        embed.set_footer(text=f'Posted by: {memePoster} | Subreddit: {memeSub} | Post: {memeLink}')
        await ctx.send(embed=embed)`

**Comment by purrre** [comment]
Any updates on this? I really need this to be resolved, or im gonna have to switch to using a different API, which I dont want to do cause this one is great and easy to use.

**Comment by imnew827** [comment]
update pls same error :/

**Comment by alemm1ng** [comment]
Seems like I'm receiving this error to. I can't find a solution too.

**Comment by purrre** [comment]
To everyone having this issue, ive found a fix. You have to switch from using urllib to using [requests](https://requests.readthedocs.io/en/latest/). Its the same concept as urllib. Ill make a tutorial eventually if i cant find one to post here.

Edit: You can read through a pretty good tutorial [here](https://www.askpython.com/python/examples/pull-data-from-an-api). If for some reason you cant figure it out, feel free to dm me on discord @ Pure.#2290

**Comment by itswilliboy** [comment]
Although you should use an async library like aiohttp to not block the event loop.
